FROM node:current-alpine AS builder

WORKDIR /app

COPY web/ .
COPY Enviroment/web/Enviroment .env

RUN npm install
RUN npm run build

FROM nginx:alpine

COPY nginx/default.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
