# Stage 1: Build
FROM golang:1.23-alpine AS builder

WORKDIR /app

COPY api/ ./
RUN go mod tidy

RUN go build -o api .

# Stage 2: Deploy
FROM alpine:latest

EXPOSE 8080

RUN apk --no-cache add ca-certificates

WORKDIR /app

COPY --from=builder /app/api .
COPY Enviroment/api/Enviroment /app/.env

ENTRYPOINT ["./api"]
