version: '3.8'

services:
  server:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    container_name: server
    expose:
      - 5000
    networks:
      - app-network

  api:
    build:
      context: ./
      dockerfile: ./api/Dockerfile
    container_name: api
    expose:
      - 8080
    networks:
      - app-network

  web:
    build:
      context: ./
      dockerfile: ./web/Dockerfile
    container_name: web
    expose:
      - 3000
    networks:
      - app-network

  nginx:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    container_name: nginx-proxy
    ports:
      - "80:80"
    depends_on:
      - server
      - api
      - web
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
