# Stage 1: Build
FROM golang:1.21-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
RUN go mod tidy

COPY . .

RUN go build -v api .

# Stage 2: Deploy
FROM alpine:latest

EXPOSE 8080

RUN apk --no-cache add ca-certificates

WORKDIR /app

COPY --from=builder /app/api .

ENTRYPOINT ["./api"]
